spring.datasource.url=jdbc:mariadb://localhost:3308/cs2800gr18_myadvice
spring.datasource.username=cs2800gr18_myadvice
spring.datasource.password=student01
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true